version: '3.8'

x-common-variables:
  PG_PORT: &PG_PORT "5432"
  PG_DB: &PG_DB "omen"
  PG_USER: &PG_USER "omen"
  PG_PASSWORD: &PG_PASSWORD "0000"

networks:
  backend:
  k6:
  grafana:

services:
  postgres:
    image: postgres:15
    volumes:
      - ./docker_test/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend
    ports:
      - *PG_PORT
    environment:
      POSTGRES_DB: *PG_DB
      POSTGRES_USER: *PG_USER
      POSTGRES_PASSWORD: *PG_PASSWORD
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U omen" ]
      interval: 10s
      timeout: 5s
      retries: 5

  
  
  my-app:
    environment:
      SPRING_PROFILES_ACTIVE: stg
      DB_HOST: postgres
      DB_PORT: *PG_PORT
      DB_DATABASE_NAME: *PG_DB
      DB_USERNAME: *PG_USER
      DB_PASSWORD: *PG_PASSWORD
    networks:
      - backend
      - k6
    build:
      context: .
    ports:
      - "8080:8080"
      - "9001:9001"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "1GB"
        reservations:
          cpus: "1.0"
          memory: "1GB"
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://my-app:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    depends_on:
      postgres:
        condition: service_healthy

  influxdb:
    image: influxdb:1.8
    networks:
      - k6
      - grafana
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6


  grafana:
    image: grafana/grafana:9.3.8
    networks:
      - grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./docker_test/grafana/provisioning:/etc/grafana/provisioning
      - ./docker_test/grafana/data:/var/lib/grafana
      - ./docker_test/grafana/plugins:/plugins

  k6:
    image: grafana/k6:latest
    networks:
      - k6
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./docker_test/k6:/home/k6/scripts
    entrypoint: [ "k6" ,"run", "./scripts/script.js" ]
    depends_on:
      my-app:
        condition: service_healthy




